name: dest
favicon: null
layout_spectrum: 0.12801689165644348
typography_spectrum: 0.14229894918389618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0681172008626163
  lightness: 0.7093628547154367
  saturation: 0.982252084184438
  rhythmicContrast: 0.6468078675679862
purpose: []
